server:
  port: 8081
spring:
  application:
    name: banking-service
  datasource:
    url: jdbc:mariadb://localhost:3306/online_banking_system
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true